version: "3"

services:
  web-tty:
    image: wrfly/container-web-tty:latest
    ports:
      - 8080:8080
    environments:
      - WEB_TTY_DEBUG: false
      - DOCKER_HOST: tcp://localhost:2323
    volume:
      - /var/run/docker.sock:/var/run/docker.sock