version: "3"

services:
  web-tty:
    image: wrfly/container-web-tty:latest
    ports:
      - 8080:8080
    environment:
      - WEB_TTY_DEBUG: "false"
      - DOCKER_HOST: "/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker